#!/usr/bin/env python3
"""Rebuild js/data.js and images/thumb/ from whatever is in images/<category>/.

Run from the project root:  python3 tools/build-manifest.py
Requires Pillow:            pip install Pillow
"""
import json
import os
import sys

from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES = os.path.join(ROOT, "images")
THUMBS = os.path.join(IMAGES, "thumb")
THUMB_EDGE = 900
THUMB_QUALITY = 80

# Display order on the roll. Any folder not listed is appended alphabetically.
ORDER = ["landscape", "architecture", "portrait", "wildlife",
         "fashion", "event", "food", "product"]


def categories():
    found = sorted(
        d for d in os.listdir(IMAGES)
        if os.path.isdir(os.path.join(IMAGES, d)) and d != "thumb"
    )
    return [c for c in ORDER if c in found] + [c for c in found if c not in ORDER]


def average_luma(im):
    small = im.convert("L").resize((16, 16))
    pixels = list(small.getdata())  # noqa: PIL deprecation is harmless here
    return sum(pixels) / len(pixels) / 255


def pick_cover(items):
    """Favour a mid-bright, roughly 3:2 frame near the start of the set."""
    best = None
    for i, it in enumerate(items):
        ratio = it["w"] / it["h"]
        score = -abs(ratio - 1.5) * 2 - abs(it["l"] - 0.42) * 1.5 - i * 0.02
        if best is None or score > best[0]:
            best = (score, it["f"])
    return best[1]


def main():
    if not os.path.isdir(IMAGES):
        sys.exit(f"No images directory at {IMAGES}")

    out = []
    for cat in categories():
        src_dir = os.path.join(IMAGES, cat)
        thumb_dir = os.path.join(THUMBS, cat)
        os.makedirs(thumb_dir, exist_ok=True)

        items = []
        for name in sorted(os.listdir(src_dir)):
            if not name.lower().endswith((".jpg", ".jpeg", ".png")):
                continue
            im = ImageOps.exif_transpose(Image.open(os.path.join(src_dir, name)))
            w, h = im.size
            scale = min(1.0, THUMB_EDGE / max(w, h))
            thumb = im.convert("RGB").resize(
                (max(1, round(w * scale)), max(1, round(h * scale))), Image.LANCZOS
            )
            thumb.save(os.path.join(thumb_dir, name), "JPEG",
                       quality=THUMB_QUALITY, optimize=True, progressive=True)
            items.append({"f": name, "w": w, "h": h, "l": round(average_luma(thumb), 3)})

        if not items:
            continue
        out.append({"id": cat, "title": cat.capitalize(),
                    "cover": pick_cover(items), "images": items})
        print(f"{cat:14s} {len(items):3d} photographs")

    target = os.path.join(ROOT, "js", "data.js")
    with open(target, "w") as fh:
        fh.write("/* Generated by tools/build-manifest.py — do not edit by hand.\n"
                 "   Real dimensions keep layout stable and let the reel lay images\n"
                 "   out by their true aspect ratio. */\n")
        fh.write("window.PORTFOLIO = " +
                 json.dumps({"categories": out}, separators=(",", ":")) + ";\n")
    print(f"\nWrote {target} — {sum(len(c['images']) for c in out)} photographs "
          f"across {len(out)} categories.")


if __name__ == "__main__":
    main()
